CREATE TABLE IF NOT EXISTS DATA_ASSET(
	ASSET_ID NUMBER PRIMARY KEY,
	ASSET_NAME VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS DATA_GROUP(
	GROUP_ID NUMBER PRIMARY KEY,
	GROUP_NAME VARCHAR(32),
	GROUP_CREAT_DATE TIMESTAMP,
	GROUP_ASSET_ID NUMBER,
	FOREIGN KEY (GROUP_ASSET_ID) REFERENCES DATA_ASSET(ASSET_ID)
);

CREATE TABLE IF NOT EXISTS DATA_ITEM(
	ITEM_ID NUMBER PRIMARY KEY,
	PROSPECT_EMAIL VARCHAR(64),
	EMAIL_ISP VARCHAR(16),
	ITEM_GROUP_ID NUMBER,
	FOREIGN KEY(ITEM_GROUP_ID) REFERENCES DATA_GROUP(GROUP_ID)
);

CREATE TABLE IF NOT EXISTS SUPPRESSION_INFO(
	SINFO_ID NUMBER PRIMARY KEY,
	SUPPRESSION_ID NUMBER NOT NULL UNIQUE,
	SUPPRESSION_LOCATION VARCHAR(128),
	SUPPRESSION_PLATFORM VARCHAR(8)
	
);

CREATE TABLE IF NOT EXISTS SUPPRESSION_FILTERED_GROUP(
	SFG_GROUP_ID NUMBER,
	SFG_SINFO_ID NUMBER,
	FILTERED_DATA_COUNT NUMBER,
	FOREIGN KEY(SFG_GROUP_ID) REFERENCES DATA_GROUP(GROUP_ID), 
	FOREIGN KEY(SFG_SINFO_ID) REFERENCES SUPPRESSION_INFO(SINFO_ID)

);


CREATE SEQUENCE IF NOT EXISTS DATA_ASSET_PK_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS DATA_GROUP_PK_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS DATA_ITEM_PK_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SUPPRESSION_INFO_PK_SEQ START WITH 1 INCREMENT BY 1;


