CREATE TABLE IF NOT EXISTS CAMPAIGN(
CMP_ID NUMBER PRIMARY KEY,
CMP_BAT_SIZE NUMBER,
CMP_BAT_INT_SEC NUMBER,
CMP_IP_ROT_CNT NUMBER,
CMP_FROM_HEAD VARCHAR,
CMP_FROM_NAME_HEAD VARCHAR,
CMP_SUB_HEAD VARCHAR,
CMP_REP_TO_HEAD VARCHAR,
CMP_BNC_ADR_HEAD VARCHAR,
CMP_RCV_HEAD VARCHAR,
CMP_ADD_HEAD VARCHAR,
CMP_MAIL_BODY VARCHAR,
CMP_MTA_IDS VARCHAR,
CMP_GRP_IDS VARCHAR,
CMP_SUPP_ID NUMBER,
CMP_OFFSET NUMBER,
CMP_LIMIT NUMBER,
CMP_IS_DATA_FIL VARCHAR,
CMP_STATUS VARCHAR
);

CREATE SEQUENCE IF NOT EXISTS CMP_ID_PK_SEQ START WITH 1 INCREMENT BY 1
